
#ifndef BATTLEGROUND_NODE_H
#define BATTLEGROUND_NODE_H

#include "Battleground.h" // Include the base class for Battlegrounds
#include "Log.h"          // For logging errors (assuming TC_LOG_ERROR is defined here)

// Enum for node types

enum BG_NODE_SPAWNTIMES
{
    NODE_RESPAWN_6 = 360,
    NODE_RESPAWN_7 = 420,
    NODE_RESPAWN_10 = 600
};

// Enum for node entries
enum BG_MINERAL_ENTRY
{//mineral
    BG_OBJECT_TIN_NODE_ENTRY  = 1732,
    BG_OBJECT_IRON_NODE_ENTRY = 1735,
    BG_OBJECT_GOLD_NODE_ENTRY = 1734,
    BG_OBJECT_MITH_NODE_ENTRY = 2040,
    BG_OBJECT_TS_NODE_ENTRY = 2047,
    BG_OBJECT_SILVER_NODE_ENTRY = 1733,
    BG_OBJECT_DIRON_NODE_ENTRY = 165658,
    BG_OBJECT_THOR_NODE_ENTRY = 324,
    BG_OBJECT_RTHOR_NODE_ENTRY = 175404,


    //flower
    BG_OBJECT_KHAD_NODE_ENTRY = 2043,
    BG_OBJECT_GRASS_NODE_ENTRY = 142142,
    BG_OBJECT_MAGE_NODE_ENTRY = 3727,
    BG_OBJECT_BRIAR_NODE_ENTRY = 1621,
    BG_OBJECT_FADE_NODE_ENTRY = 2042,
    BG_OBJECT_BLIND_NODE_ENTRY = 142143,
    BG_OBJECT_ROTUS_NODE_ENTRY = 176589,
    BG_OBJECT_THORN_NODE_ENTRY = 2046,
    BG_OBJECT_FIREB_NODE_ENTRY = 2866
};

#endif // BATTLEGROUND_NODES_H
